services:
  - type: web
    name: idosos-monitoramento
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput"
    startCommand: "gunicorn idosos_monitoramento.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: idosos_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PIP_NO_BINARY  # <-- ForÃ§a pip
        value: "all"

databases:
  - name: idosos_db
    databaseName: idosos_monitoramento
    user: idosos_user